### ISSUE TITLE
remote_params

### ISSUE THREAD

**Issue by semiaLi** [tetranz/select2entity-bundle#1]
Can i know what is the type of return that this function should be ?
'remote_route' => 'tetranz_test_default_countryquery', ?
it should be a query ? or a list ?

**Comment by tetranz** [comment]
It needs to return an array in json. It must have two elements call "id" and "text"

Here's an example controller action.

    /**
     * @Route("/country.json", name="country_select")
     */
    public function countrySelectAction(Request $request)
    {
        $q = $request->get('q');
        $pageLimit = $request->get('page_limit');

        if (!is_numeric($pageLimit) || $pageLimit > 10) {
            $pageLimit = 10;
        }

        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $result = $em->createQuery(
            'SELECT c.id, c.name as text FROM AppBundle:Country c
            WHERE lower(c.name) LIKE :q
            ORDER BY c.name')
            ->setParameter('q', '%' . $q . '%')
            ->setMaxResults($pageLimit)
            ->getArrayResult();

        return new JsonResponse($result);
    }

You can test that by pointing a browser to:
http://example.com/country.json?q=ne&page_limit=10

That will return countries with "ne" in the name.

I haven't touched this for a long time so last night I reinstalled it following my own instructions. Something that threw me is that there is a new version of Select2.  This bundle only works with version 3.5 from https://github.com/select2/select2/tree/stable/3.5. I will update the documentation.

**Comment by semiaLi** [comment]
Thanks for your answer, i hope your bundle becomes more used so that  we can benefit from it.
