### ISSUE TITLE
Options are not taken into account, remote_route don't work !

### ISSUE THREAD

**Issue by Tschuss69** [tetranz/select2entity-bundle#100]
Hello I am stuck for 3 days on a strange problem.  I have the impression that the options are not taken into account !

I followed the documentation but it don't work. 

I can display my form, but the ajax request does not point to the right route. Indeed instead of taking into account the route specified in the options it is another route that is used! Moreover I have the impression that the other options are not taken into account because the Ajax request starts as soon as we click on the input whereas I asked that it starts only from 4 characters. Does someone have an idea?

Here is the code

Help !!!

Mathieu

The Route that should be used in the ajax request. 

`datatype_coding_show_ajax_action:
    path:  /show-ajax
    defaults: { _controller: "MSFhirBundle:Coding:showAjax" }
    requirements: { _method: get|post }
    options:
        expose: true`

FormType

`<?php

namespace MS\FhirBundle\Form\DataType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\CallbackTransformer;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\DependencyInjection\Container;

use Doctrine\Common\Persistence\ObjectManager;
use MS\FhirBundle\DataTransformer\IdTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Tetranz\Select2EntityBundle\Form\Type\Select2EntityType;

class CodeableConceptType extends AbstractType
{
	
	
		
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
			->add('codings', Select2EntityType::class, array(
            'multiple' => true,
			'minimum_input_length' => 4,
            'remote_route' => 'datatype_coding_show_ajax_action',
            'class' => 'MSFhirBundle:Coding',
            'primary_key' => 'id',
            'page_limit' => 10,
            'allow_clear' => true,

        ))
			->add('text')
				;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MS\FhirBundle\Entity\DataType\CodeableConcept'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ms_fhirbundle_datatype_codeableconcept';
    }

}
`

The URL used to have the form. This URL is not the URL that should be used in the Ajax request http://localhost:8888/app_dev.php/atcd/new (symphony name : actd_new) but you can see ajax request realised by the bundle 

![capture d ecran 2017-12-10 a 14 13 20](https://user-images.githubusercontent.com/27869101/33805280-5fad082c-ddb6-11e7-8751-6acfd769c1b9.png)

**Comment by tetranz** [comment]
I setup a new test site today to work through some issues and got the same problem.  I "fixed" it by going back to jQuery 1.12.4. I'm very surprising that there are not lots of people reporting this problem. Surely other people are using jQuery 2.

Unfortunately I don't have much spare time to devote to this project these days but I'll try to do some debugging in the next week or so.

**Comment by tetranz** [comment]
I've done some more testing and finding some quite weird results.

If I make a plain html file with this, it works.  That's nothing to do with Symfony except for my ajax endpoint.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
</head>
<body>

<select data-minimum-input-length="2" data-ajax--url="http://www.symtest.local/person.json"
        style="width: 200px;" class="js-data-example-ajax"></select>

<script
        src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $('.js-data-example-ajax').select2();
</script>
</body>
</html>
```
If I change it to jQuery 2.2.4, it does not work and I get the problem report here.  data-* attributes seem to have problems. With jQuery 2, if I change data-ajax--url to data-ajax-url it starts to work but minimum-input-length is ignored. But that's weird too because data-ajax-url is supposed to be a fix for data-ajax--url not working on jQuery 1.

I'll see if I can document the issue better and raise it in Select2 issues.

**Comment by tetranz** [comment]
The problem seems to be with select2-4.0.6-rc.0.

select2-4.0.5 works fine with later versions of jQuery.  I'll report this to the select2 project.

**Comment by Tschuss69** [comment]
Great !!! It seems to work fine ! Thanks a lot ! 

Best Wishes for a 2018
