### ISSUE TITLE
TypeError: $request is undefined only in DEV environment

### ISSUE THREAD

**Issue by andrea-daru** [tetranz/select2entity-bundle#113]
While I'm using Symfony in dev environment (app_dev.php) Select2 throw _TypeError: $request is undefined_
Framework / Libraries version:

- Symfony 3.4.5
- jQuery 1.12.4
- select2 4.0.0 

I've found that in _select2entity.js_ the ajax request does not take place and immediately fail.
https://github.com/tetranz/select2entity-bundle/blob/e8236049744b2f03ee0095f3fe189878930c9e0b/Resources/public/js/select2entity.js#L58

Anyone else is experiencing the same issue? Solutions?
Thanks in advance

**Comment by benr77** [comment]
I am experiencing the same issue

- tetranz/select2entity-bundle 2.9.4
- Symfony 3.4.5
- jQuery 3.1.1
- Select2 4.0.4

Confirmed only occurs in the dev environment.

Downgrading Symfony to 3.3.16 appears to fix the issue.
Upgrading to Symfony 3.4.6 also appears to fix the issue.

**Comment by andrea-daru** [comment]
Upgrading to Symfony 3.4.6 seems to have solved the problem.
