### ISSUE TITLE
Not working at all...

### ISSUE THREAD

**Issue by b519259** [tetranz/select2entity-bundle#12]
Hi.
I'm not sure, what's wrong, but I'm pretty sure I did everything like in the documentation. Instead of SELECT field, there's just simple INPUT with `text` type. No Select2, nothing... _(screenshot and twig list from profiler at the end)_

I'll show, what I did on the test project. 

- I've got `Movie` entity with `actors` field:
- Class `Actor` has `firstName` and `surname`. Its `__toString()` returns: 
```php
$this->surname . ', ' . $this->firstName
```

- Class `Movie` has:
```php
/**
 * @var ArrayCollection
 * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Actor")
 */
    private $actors;
```
...and `getActors()`, `setActors()`, `addActor()`, `removeActor()`. everything works with `EntityType::class` in form.

- Action returning JSON search result (it's not cleaned yet, but it works):  
```php
<?php
namespace AppBundle\Controller\API\Actor;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ActorApiController extends Controller
{
    /**
     * @Route(path="/api/actor/search", name="api_actor_search")
     * @Method({"GET"})
     */
    public function searchAction(Request $request)
    {
        $searchString = $request->get('q');
        if(strlen($searchString) < 2)
            return new Response("Invalid search query", 406);

        $entityManager = $this->getDoctrine()->getManager();
        $query = $entityManager->createQuery('
            SELECT a FROM AppBundle:Actor a
            WHERE a.firstName LIKE :searchString
                OR a.surname LIKE :searchString
            ORDER BY a.surname ASC
        ')
                               ->setParameter('searchString', '%' . $searchString . '%');

        $actors = $query->getResult();
        $actorsArray = array();
        foreach($actors as $actor)
        {
            $actorsArray[] = array(
                'id' => $actor->getId(),
                'text' => $actor->__toString(),
            );
        }
        return new Response(json_encode($actorsArray), 200, array('Content-Type' => 'application/json'));
    }
}
```
- In `config.yml` at the end I added:
```yml
twig:
    form:
        resources:
            - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
```
- I generated CRUD for test with `doctrine:generate:crud` for `AppBundle:Movie`
- In form `MovieType`, i changed field `actors` to:
```php
->add('actors', 'tetranz_select2entity', array(
                'multiple' => true,
                'remote_route'=>'api_actor_search',
                'class'=>'AppBundle\Entity\Actor'
            ))
```
- at the end I simply edited `base.html.twig` (again: it's for testing purposes):
```twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/css/select2.css" rel="stylesheet"/>

    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}"/>
</head>
<body>
{% block body %}{% endblock %}
{% block javascripts %}
    <script type="application/javascript">
        var ajaxBaseUrl = '{{ url('homepage') }}';
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/js/select2.js"></script>

    {% javascripts '@TetranzSelect2EntityBundle/Resources/public/js/select2entity.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}
</body>
</html>
```
- I ran `assets:install web` and `assetic:dump`

- How it looks like: http://i.imgur.com/8pPr1v0.png

- profiler TWIG list:
```
main 8.03ms/100%
└ movie/new.html.twig 5.81ms/72%
│ └ base.html.twig 5.74ms/72%
│   └ base.html.twig::block(title)
│   └ base.html.twig::block(stylesheets)
│   └ movie/new.html.twig::block(body) 5.56ms/69%
│   │ └ form_div_layout.html.twig::block(form_start)
│   │ └ form_div_layout.html.twig::block(form_widget) 1.45ms/18%
│   │ │ └ form_div_layout.html.twig::block(form_widget_compound) 1.44ms/18%
│   │ │   └ form_div_layout.html.twig::block(widget_container_attributes)
│   │ │   └ form_div_layout.html.twig::block(form_errors)
│   │ │   └ form_div_layout.html.twig::block(form_rows) 1.20ms/15%
│   │ │   │ └ form_div_layout.html.twig::block(form_row)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_label)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_errors)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_widget)
│   │ │   │ │   └ form_div_layout.html.twig::block(form_widget_simple)
│   │ │   │ │     └ form_div_layout.html.twig::block(widget_attributes)
│   │ │   │ └ form_div_layout.html.twig::block(form_row)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_label)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_errors)
│   │ │   │ │ └ form_div_layout.html.twig::block(integer_widget)
│   │ │   │ │   └ form_div_layout.html.twig::block(form_widget_simple)
│   │ │   │ │     └ form_div_layout.html.twig::block(widget_attributes)
│   │ │   │ └ form_div_layout.html.twig::block(form_row)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_label)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_errors)
│   │ │   │ │ └ form_div_layout.html.twig::block(form_widget)
│   │ │   │ │   └ form_div_layout.html.twig::block(form_widget_simple)
│   │ │   │ │     └ form_div_layout.html.twig::block(widget_attributes)
│   │ │   │ └ form_div_layout.html.twig::block(hidden_row)
│   │ │   │   └ form_div_layout.html.twig::block(hidden_widget)
│   │ │   │     └ form_div_layout.html.twig::block(form_widget_simple)
│   │ │   │       └ form_div_layout.html.twig::block(widget_attributes)
│   │ │   └ form_div_layout.html.twig::block(form_rest)
│   │ └ form_div_layout.html.twig::block(form_end)
│   │   └ form_div_layout.html.twig::block(form_rest)
│   └ base.html.twig::block(javascripts)
└ @WebProfiler/Profiler/toolbar_js.html.twig 2.22ms/28%
  └ @WebProfiler/Profiler/base_js.html.twig
```

**Comment by tetranz** [comment]
I don't see anything obviously wrong here.

I assume you're running Symfony 2. If you're running Symfony 3, then the config.yml and the form ->add() is slightly different. See the latest documentation that I updated a few days ago.

Are you sure that the Javascript running is ending up on the page? Do a view source on your page, scroll down to the javascripts block and click on the bundle's JS file. It's easy to get Assetic wrong and find that what you thought was a good JS link is really a 404 error. 

You don't really need to use Assetic if you're having trouble with it. The following should work after console assets:install

(just on the page, not inside {% javascripts %})
```<script src="{{ asset('bundles/tetranzselect2entity/js/select2entity.js') }}"></script>```

If you checked for Javascript errors?  Look at the console in browser web tools such as Chrome Inspector.

**Comment by b519259** [comment]
Thanks for the reply.

It was Symfony 2.8.2.
I had to use my own solution, but as far as I remember, the select2entity.js script was included correctly, it just didn't have any DOM element to run on, because the input was a text field, not select.

Probably a mystery we will never figure out... :)

**Comment by benoliver999** [comment]
I'll be honest `b519259` your example works really well for me.

Noob question... does anyone know how to include a join in the controller? Here's what I'm working with:

     public function searchAction(Request $request)
        {
            $searchString = $request->get('q');
            if(strlen($searchString) < 2)
                return new Response("Invalid search query", 406);
    
            $entityManager = $this->getDoctrine()->getManager();
            $query = $entityManager->createQuery('
                SELECT a FROM AppBundle:Actor a
                WHERE a.firstName LIKE :searchString
                    OR a.surname LIKE :searchString
                ORDER BY a.surname ASC
           ')
                ->setParameter('searchString', '%' . $searchString . '%');

            $actors = $query->getResult();
            $actorsArray = array();
            foreach($actors as $actor)
            {
                $actorsArray[] = array(
                    'id' => $actor->getId(),
                    'text' => $actor->getFirstName()
                     . ' ' . 
                    $actor->getLastName()
                     . ' ' . 
                    $actor->getCompany()
                );
            }
            return new Response(json_encode($actorsArray), 200, array('Content-Type' => 'application/json'));
        }
    }

In this case `company` is an id referring to the `Company` table, I'd like to get its name with a join.

I have tried to put a join in the query but it breaks the `getId()` and `getName()` methods. I have tried to use `partial` so `SELECT partial a.{id, firstName, lastName, company}, partial b.{id, name}` but that also breaks the methods since it goes looking for them in the Company entity rather than the Actors one.

I am missing something obvious I'm sure.

**Comment by b519259** [comment]
Hi again.

It's one of those things nobody knows, why they're not working. I tried again, it's working like a charm. Just letting you know @tetranz.

**Comment by tetranz** [comment]
Thanks.
