### ISSUE TITLE
Tagging support

### ISSUE THREAD

**Issue by mkalisz77** [tetranz/select2entity-bundle#13]
Is tags supported in this bundle. this option of Select2 allow to add new values the list

See:
https://select2.github.io/examples.html (Tagging Support)

**Comment by tetranz** [comment]
No, sorry. tags are not supported. Feel free to send a PR if you can make it work without breaking backwards compatibility. 

I haven't looked closely at tags but just thinking out loud ...

Putting Select2 into tags mode would be easy to do if we add the data-tags attribute as yet another option but there is more to it than that. EntitiesToPropertyTransformer::reverseTransform would need to deal with the added items. Maybe it just needs to instantiate new entities and add them to the collection. Would that be useful?

**Comment by sharky98** [comment]
Tetranz, I've forked your bundle and added my own way of doing it. You can find it [here](https://github.com/sharky98/select24entity-bundle). I've changed the philosophy behind the bundle as being more like select2 (the user need to activate the plugin by himself in his templates), however it means the user have more control over the select2 properties. Basically, whatever Select2 support, Select24Entity will overwrite its own configuration.

This allows the tags support up to a certain limit. I've modified EntitiesToPropertyTransformer::reverseTransform to parse those new entities (the javascript append `new_` in front of them). I chose to not instantiate the new entities as they could have other properties that we are not aware of, which would break. Instead, I'm forcing the user to create its own DataTransformer (which run after EntitiesToPropertyTransformer::reverseTransform), in which he can take the new one and parse them. I've given an example in my readme.

**Comment by tetranz** [comment]
We now have tagging thanks to a pull request from @Emirii.
