### ISSUE TITLE
Implement "attributes" argument

### ISSUE THREAD

**Issue by b519259** [tetranz/select2entity-bundle#14]
Hello.

As I finally got this bundle to work... is there any chance to implement 'attr' argument, like in typical form fields? For example, I'd like to have custom CSS class on my field - right now I can't control Selec2's width and it looks like crap. It can be worked around of course, but having control over attributes would be great.

**Comment by tetranz** [comment]
It already supports attr just like any other form field. Set that to an associative array of attribute names and values. If you set a key named class it will be appended to the existing "class" attribute.

**Comment by b519259** [comment]
I'm sorry, I didn't know there are typical atributes available also for custom form field types. Thanks for the information.
