### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by Fl0ux** [tetranz/select2entity-bundle#147]
![select2entity](https://user-images.githubusercontent.com/545615/60871211-95650180-a232-11e9-9167-b658ef15b180.png)

**Comment by tetranz** [comment]
I guess this is related to this https://github.com/tetranz/select2entity-bundle/pull/146 which changed to PSR-4. I was a little concerned about that and wondered if I should have called it version 3.

Try `composer dump-autoload`

If that doesn't work then at least temporarily you could go back to version 2.9.6.

**Comment by Fl0ux** [comment]
If I run `composer dump-autoload` and then `composer update` I have the same error.

**Comment by rumours86** [comment]
i removed all cache - it fixed error

**Comment by Fl0ux** [comment]
`./bin/console cache:clear` seems to resolve the problem.

**Comment by konradja100** [comment]
> I guess this is related to this #146 which changed to PSR-4. I was a little concerned about that and wondered if I should have called it version 3.
> 
> Try `composer dump-autoload`
> 
> If that doesn't work then temporarily you could go back to version 2.9.6. If more people report this then I may have to revert back to PSR-0.

This error is still appearing, due to our autodeploy scripts we can't run ```composer dump-autoload```, so it would be great to move back to PSR-0.
