### ISSUE TITLE
Error with doctrine/persistence 2.0.0

### ISSUE THREAD

**Issue by Knallcharge** [tetranz/select2entity-bundle#169]
Hi,

after upgrading doctrine/doctrine-bundle to version 2.1.2 (from 2.1.0) which comes with doctrine/persistence 2.0.0, the bundle stopped working. The error I'm getting is:

Argument 1 passed to Tetranz\Select2EntityBundle\Form\Type\Select2EntityType::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given

Quick fix for now: Adding "doctrine/persistence": "^1" to my composer.json will allow me to update the doctrine-bundle, but I think in the long run, doctrine/persistence should be supported.

**Comment by fabian-laine** [comment]
+1
