### ISSUE TITLE
The option "transformer " does not exist

### ISSUE THREAD

**Issue by poneymagique** [tetranz/select2entity-bundle#18]
I don't manage to use the transfomer option... based on the last commit, don't get why

**Comment by poneymagique** [comment]
i'm on symfony 2.8

**Comment by tetranz** [comment]
I haven't tagged a new release yet.

Try it with dev-master in your composer.json. I'll tag a new release in the next week or so then you'll be able to put it back to 2.*

**Comment by poneymagique** [comment]
yeah i'm trying, i tried to checkout your last commit with composer, but i think it was not correctly loaded, i'm trying now with dev master

**Comment by poneymagique** [comment]
i tried this dev#02c44460695efc4ad579dc626e1123cd377a15cc and devmaster only, but it does not work

**Comment by poneymagique** [comment]
dev-master evry time, just typo in my comment, the source code is present

**Comment by tetranz** [comment]
I just tried it now and it definitely works for me if set it to dev-master. I must admit that I hadn't tried it as a normal composer dependency since that commit but it works fine. Sorry, I know that's not a very helpful response.

Do you get the typical error page which lists all the possible options, there must be about 30 of them, and "transformer" is not one of them?

It looks like you're somehow getting an earlier version. Have you tried deleting the vendor/tetranz directory and running composer update again?

**Comment by poneymagique** [comment]
yeah i get the typical page, it says it does not exist but transformer is in the list... i don't get why

**Comment by tetranz** [comment]
Take a look in [Select2EntityType.php](https://github.com/tetranz/select2entity-bundle/blob/master/Form/Type/Select2EntityType.php). Near the bottom, does the configureOptions include `'transformer' => null`? Also, further up, in buildForm, you should see the new code for transformer. That will tell us if you're getting the wrong version or something else is happening.

**Comment by poneymagique** [comment]
all is present

**Comment by tetranz** [comment]
Well ... I don't know. If I purposely try to set a bogus option in my form builder I get this:

` The option "bogus" does not exist. Defined options are: "action", "allow_clear", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "cache", "class", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "delay", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "language", "mapped", "method", "minimum_input_length", "multiple", "page_limit", "placeholder", "post_max_size_message", "primary_key", "property_path", "remote_params", "remote_path", "remote_route", "required", "static_control", "text_property", "transformer", "translation_domain", "trim", "validation_groups".
500 Internal Server Error - UndefinedOptionsException`

I know you said "transformer" is not there but are the others relevant to this bundle there? I mean things like "minimum_input_length", "primary_key", "property_path", "remote_params", "remote_path", "remote_route".

I'm really just poking around in the dark here trying to figure out what might be happening. I am using Symfony 3.0 but it should work on 2.8.  Unfortunately I don't have a 2.8 installation that I can quickly try it on. Maybe @tmisheva can say what version that update was tested with.

**Comment by poneymagique** [comment]
well me too, and deleting the dependency + adding don't work too... I'll try an upgrade to symfony 3, to test

**Comment by poneymagique** [comment]
well it's to complicated to migrate for me now, i'll do some other tests

**Comment by poneymagique** [comment]
i used it another way without transformer (bit dirty but it works)

**Comment by poneymagique** [comment]
I wonder also how to update remote route param on field change

**Comment by poneymagique** [comment]
i close this

**Comment by tmisheva** [comment]
[My fork](https://github.com/tmisheva/select2entity-bundle) works with Symfony 2.7.10
Now I'll try [the new release](https://github.com/tetranz/select2entity-bundle/releases/tag/v2.4) with Symfony 2.8

/cc @poneymagique @tetranz

**Comment by poneymagique** [comment]
@tmisheva you should provider a pull request that'll be great, i use it in a way that solved my problem because in my app it's coupled with another bundle, i'll take a look , thank you for your work

**Comment by tmisheva** [comment]
My [pull request](https://github.com/tetranz/select2entity-bundle/pull/16) is already merged and the code should be in [version 2.4](https://github.com/tetranz/select2entity-bundle/compare/v2.3...master).

After I changed composer.json to be `"tetranz/select2entity-bundle": "~2.4"` and run `composer update` it works with Symfony 2.8.4 for me. 
In [Custom option text](https://github.com/tetranz/select2entity-bundle#custom-option-text) section you can see a custom transformer example.

@poneymagique tell me if I can help with something else.

**Comment by poneymagique** [comment]
@tmisheva ohh :) thank you, if you have some time I have another issue about upload a route on Ajax, i did not have the time to investigate much, it's on my agenda but if you are free help is really appreciated :) Just if you have time, i'll try to provide a solution if you don't have

**Comment by tmisheva** [comment]
I'm sorry I missed this comment :)
