### ISSUE TITLE
unable to update route of select2

### ISSUE THREAD

**Issue by poneymagique** [tetranz/select2entity-bundle#19]
i have chained select, but i'm anable to update the route depending on first select.. I tried this

                $.fn.select2entityAjax = function(action) {
                var action = action || {};
                this.select2($.extend(action, {
                    ajax: {
                        url: function () {
                            return  Routing.generate('subactivity_list', {  _locale: '{{ app.request.locale }}', id: $('#company_activity').val() });
                        },
                        data: function (params) {
                            return {
                                q: params.term
                            };
                        },
                        processResults: function (data) {
                            return {
                                results: data
                            };
                        }
                    }
                }));
                return this;
            };
            $('#company_subactivities').select2entityAjax();

            $('#company_activity').on('change', function(){
                activity = $(this).val();
                var locale = '{{ app.request.locale }}' ;
                route = Routing.generate('subactivity_list', {_locale: locale, id: activity  });
                $('#company_subactivities').attr('data-ajax--url', route);
                $('#company_subactivities').attr('ajax--url', route);

            });
        });

Can you provide some info?

**Comment by tetranz** [comment]
Sorry, I can't really help. I've never tried anything like that. Maybe someone else has an idea.

**Comment by poneymagique** [comment]
i'll try to solve this, and provide solution here
