### ISSUE TITLE
Select2 4.0 compability problem

### ISSUE THREAD

**Issue by ismailbaskin** [tetranz/select2entity-bundle#2]
Select2 4.0 announced "no more hidden input tags" for advanced usage https://select2.github.io/announcements-4.0.html#hidden-input . It's using select tag instead for type=hidden

**Comment by tetranz** [comment]
Thanks but I haven't really looked at Select2 version 4.  I don't have much spare time right now but I hope to get around to making it version 4 compatible.

**Comment by ismailbaskin** [comment]
https://github.com/tetranz/select2entity-bundle/pull/4
