### ISSUE TITLE
select 3.x compatibility

### ISSUE THREAD

**Issue by younes0** [tetranz/select2entity-bundle#20]
This bundle generate a "select" which is not compatible with select2 Ajax option, I get this error:
`Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.`
I don't get this error with select2 4.x , but I can't upgrade to 4.x.

**Comment by tetranz** [comment]
Version 1.1 of this bundle works with Select2 version 3. It doesn't have the newer options but it supports most of the basic Select2 operation.
