### ISSUE TITLE
Please tag release 2.5 (or 2.4.1)

### ISSUE THREAD

**Issue by lifo101** [tetranz/select2entity-bundle#24]
I need your PHP v5.4 compat fixes, but don't want to use `dev-master` in my project's composer for your library (I don't want to fork your master either; I'm lazy). Thanks =)

Thanks for the shout-out for `lifo/typeahead-bundle`, btw. =)

**Comment by tetranz** [comment]
Done.  2.5

Sorry, I should have done that earlier.

**Comment by lifo101** [comment]
awesome, thanks
