### ISSUE TITLE
Use EntityManagerInterface instead of EntityManager

### ISSUE THREAD

**Issue by Tetdoss** [tetranz/select2entity-bundle#27]
Hello :)

Can you please use EntityManagerInterface instead of EntityManager in your constructors, because I have my own EntityManager and I can't use it with your bundle.

Thank you !

**Comment by tetranz** [comment]
Done. Good point. It's on master. If it looks good I'll tag it as 2.52.

I bumped up the Doctrine requirement to >= 2.4. I hope that doesn't cause any problems.

**Comment by Tetdoss** [comment]
Works like expected ! Thank you for being so fast ;)

**Comment by tetranz** [comment]
Cool. I just released v2.52.
