### ISSUE TITLE
Shouldn't return ArrayCollection in EntitiesToPropertyTransformer

### ISSUE THREAD

**Issue by lifo101** [tetranz/select2entity-bundle#31]
In your [EntitiesToPropertyTransformer](https://github.com/tetranz/select2entity-bundle/blob/master/Form/DataTransformer/EntitiesToPropertyTransformer.php#L79) you return an `ArrayCollection` instead of an empty array when the $value is empty. I'm pretty sure you simply want to return an empty array instead of the collection. For one, you can't assume people will be using Doctrine, and second, I end up having to do something like this in some of my code that uses a select2 filter:

```
$form->handleRequest($request);
if ($form->isValid()) {
    $filter = $form->getData();
    // fix Select2EntityType nuance 
    if (($filter['tags'] instanceof ArrayCollection) && $filter['tags']->count() == 0) {
        $filter['tags'] = null;
    }
}
```

**Comment by tetranz** [comment]
Yes, you're quite correct. I don't know why I thought that an ArrayCollection was the thing to return.

I've fixed it on master. I'll tag a new release in a few days.

**Comment by FlorentinGarnier** [comment]
Sorry for the dig up. But, are you sure it's the best way ? Because Select2EntityType seam to have the same behavior of an EntityType is to return an ArrayCollection ?
