### ISSUE TITLE
Not working with non default entity manager

### ISSUE THREAD

**Issue by mitch10593** [tetranz/select2entity-bundle#58]
In my application, I'm using entities from Default Entity manager, and also from alternative entity manager.

select2entity-bundle seems to work only on default entity manager.

Suggestion: do not inject entity manager, but doctrine service.
Use manager name instead of entity manager to handle EntityPropertyTransformer (and, by default, use "default" for this manager name).

**Comment by tetranz** [comment]
Sorry, I haven't had much time to deal with issues here recently.
I'm not sure if I know the correct thing to do here. I'm happy to consider a pull request.
