### ISSUE TITLE
[Feature] Add cache clear option

### ISSUE THREAD

**Issue by michalkurzeja** [tetranz/select2entity-bundle#60]
The cache option is very useful, however on some occasions it is necessary to clear the cache manually (e.g. if we know that the remote data has changed). Currently the only way is to set extremely low cache timeout (bad), disable cache entirely (also not great) or to override `ajax.transport` function and override the caching layer. It would be great to have a function that would clear the cache on demand for us.

Example call:
```
    $element.select2entity("clear-cache");
```

This should completely clear the cache array.

**Comment by tetranz** [comment]
That sounds like a good idea. I'll take a look at it but feel free to submit a PR.

I just released 2.8.1
