### ISSUE TITLE
Unable to generate a URL for the named route  "" in Symfony 3.2

### ISSUE THREAD

**Issue by Itaelle** [tetranz/select2entity-bundle#71]
Hello,

When adding this field
```
            ->add('company', Select2EntityType::class, [
                'class' => 'ApiBundle:Company',
                'primary_key' => 'id',
                'multiple' => false,
                'text_property' => 'name',
                'minimum_input_length' => 2,
                'allow_clear' => true,
                'placeholder' => 'Select a Company',
                'required' => false,
                'empty_data' => null,
            ])
```

I get the following error: 
![image](https://cloud.githubusercontent.com/assets/1116475/23945169/c55684ac-0975-11e7-90ac-e97d9e2ab97c.png)

Even if i remove all options from the field and do a simple
 ` ->add('company', Select2EntityType::class, [])` i would get the error. 

If I remove the field or put a regular entity field everything works perfectly.
The bundle is itself properly installed. 

Any leads on where that could come from?

Thanks guys!

**Comment by Schyzophrenic** [comment]
If you want to use Ajax you need to set the remote route in your parameters.

Le 15 mars 2017 6:55 PM, "Augustin Pasquini" <notifications@github.com> a
écrit :

**Comment by Itaelle** [comment]
Yeah I just realised that!
I don't want to use Ajax, though! That's the point!

**Comment by Itaelle** [comment]
I see there's a merge request currently for that feature https://github.com/tetranz/select2entity-bundle/pull/68 , it would be indeed nice to merge it! 😄

**Comment by Schyzophrenic** [comment]
On that case there is an unfinished PR (still requires polishing) #68

Le 15 mars 2017 7:00 PM, "Augustin Pasquini" <notifications@github.com> a
écrit :
