### ISSUE TITLE
Unable to re submit the form if the the select allows (and contains) a new entry

### ISSUE THREAD

**Issue by Seb33300** [tetranz/select2entity-bundle#75]
Hi,

When adding a `Select2EntityType` field with `allow_add` option enabled.

If we add a new value:

When we submit the form for the first time, the select value is submitted with the `new_tag_prefix`
Ex: `__myvalue`

But if the form submission fails, the select is refilled without the `new_tag_prefix`.
So the submitted value will be `myvalue` insteaf of `__myvalue`.

So the form submission will fails because Select2Entity is not able to know that this is a new value submitted.

Is it  bug or maybe I have missed something in the configuration?

I can solve this by persisting the new added entity on form submit even if the submission fails.
But I wish to persist it only if the form submission is valid.

Seb

**Comment by Seb33300** [comment]
I looked at the code.

When a new entry is added, on submit, the entity is created without the new_tag_prefix (this is ok), then, the form is rendered with the entity value (this is not ok).

In the finishView method, the new_tag_prefix should be added to the input value if it's an added entry. So the form will be rendered with the prefix and the entity will keep the correct value (without the prefix).

**Comment by Seb33300** [comment]
I just create a pull request to fix this issue.

**Comment by Seb33300** [comment]
Fixed by https://github.com/tetranz/select2entity-bundle/pull/80

**Comment by Seb33300** [comment]
Reopened, please see: https://github.com/tetranz/select2entity-bundle/pull/81

**Comment by VyctoryaStar** [comment]
Hi,
for me this breaks resubmitting existing entities if tags are not allowed.
It worked till 2.9.2 but is broken with 2.9.3.
An error is thrown in the EntityToPropertyTransformer around line 100.
Vyctorya

**Comment by Seb33300** [comment]
Can you provide more details?
I am not able to reproduce your issue.
