### ISSUE TITLE
select2 is not working for me in symfony2.7

### ISSUE THREAD

**Issue by manoj815** [tetranz/select2entity-bundle#8]
Below is the form when i remove the  tetranz_select2entity this is working. i have check json url in separate url it also woking fine. every time an error displayed PropertyAccessor requires a graph of objects or arrays to operate on i try to resolve the problem but failed i check EntityToPropertyTransformer class and print the entity it return 0.
following is the Formtype
$builder->add('outletid', 'entity', array(
                    'multiple' => false,
                    #'remote_route' => 'admin_notification_outletjson',
                    'class' => 'Application\FreemonyBundle\Entity\Outlet',
//                    'text_property' => 'email',
//                    'minimum_input_length' => 2,
//                    'page_limit' => 10,
                    'placeholder' => 'Select a country',
        ));

**Comment by CoLzAk** [comment]
I actually using it with symfony 2.7
Here's a working example:
->add('school', 'tetranz_select2entity', [
                    'class' => 'AppBundle:School',
                    'remote_route' => 'select2_schools',
                    'placeholder' => 'choose',
                    'label' => 'choose school',
                    'text_property' => 'name',
                    'minimum_input_length' => 0,
                    'page_limit' => 10,
                    'language' => 'fr',
                    'required' => true,
])

The route select2_school returns a JSON response like this:
[{"id":1,"text":"Ecole 1"},{"id":2,"text":"Ecole 2"}]

Make sure the bundle is correctly registered, and the JSON response must contain ID and TEXT attributes (so if your entity does not have the TEXT attribute, you should alias it with a DQL).

Hope it helps.
Regards,

**Comment by manoj815** [comment]
i followed the all step but same  getting same problem.

**Comment by CoLzAk** [comment]
Can you show your entities (the Outlet and the one the form is called from) ?

**Comment by manoj815** [comment]
yes Sure
<?php

namespace Application\FreemonyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Outlet
 *
 * @ORM\Table(name="freemoni_outlet")
 * @ORM\Entity(repositoryClass="Application\FreemonyBundle\Repository\OutletRepository")
 * @UniqueEntity("email",message="This email is already in use.")
 */
class Outlet {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="shopId", type="integer")
     */
    private $shopId;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255)
     *  
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="neighbourhood", type="string", length=255)
     */
    private $neighbourhood;

    /**
     * @var integer
     *
     * @ORM\Column(name="postalcode", type="integer")
     *  
     */
    private $postalcode;

    /**
     * @var string
     *
     * @ORM\Column(name="phoneno", type="string", length=20)
     * 
     */
    private $phoneno;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=20)
     *  
     */
    private $city;

    /**
     * @var integer
     *
     * @ORM\Column(name="countryId", type="integer")
     * @ORM\ManyToOne(targetEntity="Application\AdminBundle\Entity\CmsCountryTranslation", inversedBy="Outlet")
     * @ORM\JoinColumn(name="countryId", referencedColumnName="id")
     *  
     */
    private $countryId;

    /**
     * @var integer
     *
     * @ORM\Column(name="stateId", type="integer")
     *  
     */
    private $stateId;

    /**
     * @var integer
     *
     * @ORM\Column(name="mallId", type="integer")
     */
    private $mallId;

    /**
     * @var string
     *
     * @ORM\Column(name="verificationCode", type="string", length=255)
     */
    private $verificationCode;

    /**
     * @var boolean
     *
     * @ORM\Column(name="approvedStatus", type="boolean")
     */
    private $approvedStatus;

    /**
     * @var boolean
     *
     * @ORM\Column(name="activeStatus", type="boolean")
     */
    private $activeStatus;

    /**
     * @var boolean
     *
     * @ORM\Column(name="deleteStatus", type="boolean")
     */
    private $deleteStatus;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdDate", type="date")
     */
    private $createdDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="modifiedDate", type="date")
     */
    private $modifiedDate;

    /**
     * @var string
     *
     * @ORM\Column(name="floor", type="string", length=255)
     */
    private $floor;

    /**
     * @var string
     *
     * @ORM\Column(name="apartment", type="string", length=255)
     *  
     */
    private $apartment;

    /**
     * @var string
     *
     * @ORM\Column(name="website", type="string", length=255)
     */
    private $website;

    /**

     * @ORM\Column(name="latitude", type="decimal")
     */
    private $latitude;

    /**

     * @ORM\Column(name="longitude", type="decimal")
     */
    private $longitude;

    function __construct() {

        $this->address = null;
        $this->postalcode = null;
        $this->password = md5($this->password);
        $this->apartment = null;
        $this->floor = null;
        $this->mallId = 0;
        $this->countryId = 0;
        $this->stateId = 0;
        $this->latitude = 0;
        $this->longitude = 0;
        $this->city = null;
        $this->neighbourhood = null;
        $this->createdDate = new \DateTime;
        $this->modifiedDate = new \DateTime;
        $this->activeStatus = 0;
        $this->deleteStatus = 0;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set shopId
     *
     * @param integer $shopId
     *
     * @return Outlet
     */
    public function setShopId($shopId) {
        $this->shopId = $shopId;

        return $this;
    }

    /**
     * Get shopId
     *
     * @return integer
     */
    public function getShopId() {
        return $this->shopId;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Outlet
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return Outlet
     */
    public function setPassword($password) {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * Set address
     *
     * @param string $address
     *
     * @return Outlet
     */
    public function setAddress($address) {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string
     */
    public function getAddress() {
        return $this->address;
    }

    /**
     * Set neighbourhood
     *
     * @param string $neighbourhood
     *
     * @return Outlet
     */
    public function setNeighbourhood($neighbourhood) {
        $this->neighbourhood = $neighbourhood;

        return $this;
    }

    /**
     * Get neighbourhood
     *
     * @return string
     */
    public function getNeighbourhood() {
        return $this->neighbourhood;
    }

    /**
     * Set postalcode
     *
     * @param integer $postalcode
     *
     * @return Outlet
     */
    public function setPostalcode($postalcode) {
        $this->postalcode = $postalcode;

        return $this;
    }

    /**
     * Get postalcode
     *
     * @return integer
     */
    public function getPostalcode() {
        return $this->postalcode;
    }

    /**
     * Set phoneno
     *
     * @param string $phoneno
     *
     * @return Outlet
     */
    public function setPhoneno($phoneno) {
        $this->phoneno = $phoneno;

        return $this;
    }

    /**
     * Get phoneno
     *
     * @return string
     */
    public function getPhoneno() {
        return $this->phoneno;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return Outlet
     */
    public function setCity($city) {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity() {
        return $this->city;
    }

    /**
     * Set countryId
     *
     * @param integer $countryId
     *
     * @return Outlet
     */
    public function setCountryId($countryId) {
        $this->countryId = $countryId;

        return $this;
    }

    /**
     * Get countryId
     *
     * @return integer
     */
    public function getCountryId() {
        return $this->countryId;
    }

    /**
     * Set stateId
     *
     * @param integer $stateId
     *
     * @return Outlet
     */
    public function setStateId($stateId) {
        $this->stateId = $stateId;

        return $this;
    }

    /**
     * Get stateId
     *
     * @return integer
     */
    public function getStateId() {
        return $this->stateId;
    }

    /**
     * Set mallId
     *
     * @param integer $mallId
     *
     * @return Outlet
     */
    public function setMallId($mallId) {
        $this->mallId = $mallId;

        return $this;
    }

    /**
     * Get mallId
     *
     * @return integer
     */
    public function getMallId() {
        return $this->mallId;
    }

    /**
     * Set verificationCode
     *
     * @param string $verificationCode
     *
     * @return Outlet
     */
    public function setVerificationCode($verificationCode) {
        $this->verificationCode = $verificationCode;

        return $this;
    }

    /**
     * Get verificationCode
     *
     * @return string
     */
    public function getVerificationCode() {
        return $this->verificationCode;
    }

    /**
     * Set approvedStatus
     *
     * @param boolean $approvedStatus
     *
     * @return Outlet
     */
    public function setApprovedStatus($approvedStatus) {
        $this->approvedStatus = $approvedStatus;

        return $this;
    }

    /**
     * Get approvedStatus
     *
     * @return boolean
     */
    public function getApprovedStatus() {
        return $this->approvedStatus;
    }

    /**
     * Set activeStatus
     *
     * @param boolean $activeStatus
     *
     * @return Outlet
     */
    public function setActiveStatus($activeStatus) {
        $this->activeStatus = $activeStatus;

        return $this;
    }

    /**
     * Get activeStatus
     *
     * @return boolean
     */
    public function getActiveStatus() {
        return $this->activeStatus;
    }

    /**
     * Set deleteStatus
     *
     * @param boolean $deleteStatus
     *
     * @return Outlet
     */
    public function setDeleteStatus($deleteStatus) {
        $this->deleteStatus = $deleteStatus;

        return $this;
    }

    /**
     * Get deleteStatus
     *
     * @return boolean
     */
    public function getDeleteStatus() {
        return $this->deleteStatus;
    }

    /**
     * Set createdDate
     *
     * @param \DateTime $createdDate
     *
     * @return Outlet
     */
    public function setCreatedDate($createdDate) {
        $this->createdDate = $createdDate;

        return $this;
    }

    /**
     * Get createdDate
     *
     * @return \DateTime
     */
    public function getCreatedDate() {
        return $this->createdDate;
    }

    /**
     * Set modifiedDate
     *
     * @param \DateTime $modifiedDate
     *
     * @return Outlet
     */
    public function setModifiedDate($modifiedDate) {
        $this->modifiedDate = $modifiedDate;

        return $this;
    }

    /**
     * Get modifiedDate
     *
     * @return \DateTime
     */
    public function getModifiedDate() {
        return $this->modifiedDate;
    }

    /**
     * Set floor
     *
     * @param string $floor
     *
     * @return Outlet
     */
    public function setFloor($floor) {
        $this->floor = $floor;

        return $this;
    }

    /**
     * Get floor
     *
     * @return string
     */
    public function getFloor() {
        return $this->floor;
    }

    /**
     * Set apartment
     *
     * @param string $apartment
     *
     * @return Outlet
     */
    public function setApartment($apartment) {
        $this->apartment = $apartment;

        return $this;
    }

    /**
     * Get apartment
     *
     * @return string
     */
    public function getApartment() {
        return $this->apartment;
    }

    /**
     * Set website
     *
     * @param string $website
     *
     * @return Outlet
     */
    public function setWebsite($website) {
        $this->website = $website;

        return $this;
    }

    /**
     * Get website
     *
     * @return string
     */
    public function getWebsite() {
        return $this->website;
    }

    function getLatitude() {
        return $this->latitude;
    }

    function getLongitude() {
        return $this->longitude;
    }

    function setLatitude($latitude) {
        $this->latitude = $latitude;
    }

    function setLongitude($longitude) {
        $this->longitude = $longitude;
    }
    public function __toString() {
       return $this->getEmail();
    }


}

**Comment by CoLzAk** [comment]
If you could style your answer it would be more easy to read. Can you edit your comment and also add the other entity which is related to the outlet please ?

**Comment by manoj815** [comment]
<?php
namespace Application\FreemonyBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
 
class Outlet {
    private $id;
    private $shopId;
    private $email;
    private $password;
    private $neighbourhood;
   private $postalcode;
   private $phoneno;
   private $city;
 private $countryId;
 private $stateId;
 private $mallId;
private $verificationCode;
private $approvedStatus;
 private $activeStatus;
private $deleteStatus;
private $createdDate;
private $modifiedDate;
 private $floor;
 private $apartment;
 private $website;
 private $latitude;
 private $longitude;
  function __construct() {
 $this->createdDate = new \DateTime;
        $this->modifiedDate = new \DateTime;
        $this->activeStatus = 0;
        $this->deleteStatus = 0;
    }

  public function getId() {
        return $this->id;
    }
 
    public function setShopId($shopId) {
        $this->shopId = $shopId;

        return $this;
    }
   public function getShopId() {
        return $this->shopId;
} 
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

     
    public function getEmail() {
        return $this->email;
    }

    
    public function setPassword($password) {
        $this->password = $password;

        return $this;
    }

     
    public function getPassword() {
        return $this->password;
    }

    
    public function setAddress($address) {
        $this->address = $address;

        return $this;
    }

     
    public function getAddress() {
        return $this->address;
    }

     
    public function setNeighbourhood($neighbourhood) {
        $this->neighbourhood = $neighbourhood;

        return $this;
    }

     
    public function getNeighbourhood() {
        return $this->neighbourhood;
    }
 
    public function setPostalcode($postalcode) {
        $this->postalcode = $postalcode;

        return $this;
    }
  public function getPostalcode() {
        return $this->postalcode;
    }

    public function setPhoneno($phoneno) {
        $this->phoneno = $phoneno;

        return $this;
    }
   
    public function getPhoneno() {
        return $this->phoneno;
    }

    
    public function setCity($city) {
        $this->city = $city;

        return $this;
    }

    
    public function getCity() {
        return $this->city;
    }

     
    public function setCountryId($countryId) {
        $this->countryId = $countryId;

        return $this;
    }

     
    public function getCountryId() {
        return $this->countryId;
    }

   
    public function setStateId($stateId) {
        $this->stateId = $stateId;

        return $this;
    }

    
    public function getStateId() {
        return $this->stateId;
    }

   
    public function setMallId($mallId) {
        $this->mallId = $mallId;

        return $this;
    }

    
    public function getMallId() {
        return $this->mallId;
    }

    
    public function setVerificationCode($verificationCode) {
        $this->verificationCode = $verificationCode;

        return $this;
    }

     
    public function getVerificationCode() {
        return $this->verificationCode;
    }

    
    public function setApprovedStatus($approvedStatus) {
        $this->approvedStatus = $approvedStatus;

        return $this;
    }
 
    public function getApprovedStatus() {
        return $this->approvedStatus;
    }
 
    public function setActiveStatus($activeStatus) {
        $this->activeStatus = $activeStatus;

        return $this;
    }

     
    public function getActiveStatus() {
        return $this->activeStatus;
    }

     
    public function setDeleteStatus($deleteStatus) {
        $this->deleteStatus = $deleteStatus;

        return $this;
    }

     
    public function getDeleteStatus() {
        return $this->deleteStatus;
    }

     
    public function setCreatedDate($createdDate) {
        $this->createdDate = $createdDate;

        return $this;
    }

   
    public function getCreatedDate() {
        return $this->createdDate;
    }

    
    public function setModifiedDate($modifiedDate) {
        $this->modifiedDate = $modifiedDate;

        return $this;
    }

    
    public function getModifiedDate() {
        return $this->modifiedDate;
    }

     
    public function setFloor($floor) {
        $this->floor = $floor;

        return $this;
    }

     
    public function getFloor() {
        return $this->floor;
    }

    
    public function setApartment($apartment) {
        $this->apartment = $apartment;

        return $this;
    }

    
    public function getApartment() {
        return $this->apartment;
    }

     
    public function setWebsite($website) {
        $this->website = $website;

        return $this;
    }

     
    public function getWebsite() {
        return $this->website;
    }

    function getLatitude() {
        return $this->latitude;
    }

    function getLongitude() {
        return $this->longitude;
    }

    function setLatitude($latitude) {
        $this->latitude = $latitude;
    }

    function setLongitude($longitude) {
        $this->longitude = $longitude;
    }
    public function __toString() {
       return $this->getEmail();
    }


}

**Comment by CoLzAk** [comment]
In your form, where does 'outletid' comes from ?
```
$builder->add('outletid', 'entity', array(
'multiple' => false,
#'remote_route' => 'admin_notification_outletjson',
'class' => 'Application\FreemonyBundle\Entity\Outlet',
// 'text_property' => 'email',
// 'minimum_input_length' => 2,
// 'page_limit' => 10,
'placeholder' => 'Select a country',
));
```

**Comment by manoj815** [comment]
Application\FreemonyBundle\Entity\Outlet is the entity which generate drop down

**Comment by CoLzAk** [comment]
Do you have the same issue if you try to invoke the form from a controller ?

OutletController.php
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

   // ... 

    /**
     * @Route("/test", name="test")
     */
    public function testAction(Request $request) {
        $form = $this->get('form.factory')->createBuilder()
            ->add('outletid', 'tetranz_select2entity', [
                'class' => 'Application\FreemonyBundle\Entity\Outlet',
                'remote_route' => 'admin_notification_outletjson',
                'placeholder' => 'choose',
                'label' => 'choose',
                'text_property' => 'email',
                'minimum_input_length' => 2,
                'page_limit' => 10,
            ])
            ->getForm();

        return $this->render('YourBundle:Outlet:test.html.twig', [
            'form' => $form->createView(),
        ]);
    }
```

And the view

```
    {{ form_start(form) }}
    {{ form_rest(form) }}
    {{ form_end(form) }}
```

**Comment by tetranz** [comment]
Is there another entity which has a ManyToOne relationship to Outlet? That is how this is typically used.  The other entity should have setOutlet() and getOutlet() methods.  The name of the property, i.e., the first parameter in $builder->add() would then be 'outlet', not 'outletid'.
